### ISSUE TITLE
IP/hostname

### ISSUE THREAD

**Issue by vKryptic** [TwitchedApp/twitched-extension#2]
When trying to cast from chrome to twitched zero, where can i find that information

**Comment by vKryptic** [comment]
The ip/hostname that is, ive scoured the info tab on my roku. None of them worked

**Comment by opencma** [comment]
The Roku's IP address can be found under _Settings > Network > About_. If it does not work, [this Roku support article](https://support.roku.com/article/115001480188-why-does-the-roku-mobile-app-not-see-my-roku-streaming-device-) may help.
